name: npm publish

on:
    workflow_call:
        inputs:
            node-version:
                required: false
                type: string
                default: 12.x

            dry-run:
                required: false
                type: boolean

            check-commit-signature:
                required: false
                type: boolean
                default: true

            pgp-key-id:
                required: false
                type: string
                default: E51989A3E7A27FDF

            pgp-key-server:
                required: false
                type: string
                default: hkp://keyserver.ubuntu.com

        secrets:
            npm-access-token:
                required: true

jobs:
    publish:
        runs-on: ubuntu-latest
        if: success() && github.event.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '#npm-publish')

        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 1

            -   name: Verify commit signature
                if: ${{ inputs.check-commit-signature }}
                working-directory: .
                env:
                    COMMIT_HASH: ${{ github.event.head_commit.id }}
                    KEY_ID: ${{ inputs.pgp-key-id }}
                    KEY_SERVER: ${{ inputs.pgp-key-server }}
                run: |
                    mkdir ~/.gnupg
                    chmod 700 ~/.gnupg
                    echo "trusted-key 0x$KEY_ID" >> ~/.gnupg/gpg.conf
                    gpg --no-tty --keyserver "$KEY_SERVER" --recv-keys "$KEY_ID"

                    git_logline=$(git log --pretty="format:%h %G? %GK" -1 $COMMIT_HASH)
                    logline_hash=$(echo $git_logline | cut -d' ' -f1)
                    logline_sigok=$(echo $git_logline | cut -d' ' -f2)
                    logline_sigfp=$(echo $git_logline | cut -d' ' -f3)

                    echo "Verifying commit info: $logline_hash / $logline_sigok / $logline_sigfp"

                    if [[ $COMMIT_HASH != $logline_hash* ]]; then
                        echo "Verified commit hash $logline_hash doesn't match workflow hash $COMMIT_HASH"
                        exit 1
                    fi

                    if [ $logline_sigok != "G" ]; then
                        echo "Commit signature status is not 'G': $logline_sigok"
                        exit 2
                    fi

                    if [ $logline_sigfp != "$KEY_ID" ]; then
                        echo "Commit signature key id $logline_sigfp does not match expected $KEY_ID"
                        exit 3
                    fi

                    echo "Commit signature OK"

            -   name: Use Node.js ${{ inputs.node-version }}
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ inputs.node-version }}

            -   name: npm install
                run: npm install

            -   name: npm publish
                uses: JS-DevTools/npm-publish@v3
                with:
                    token: ${{ secrets.npm-access-token }}
                    dry-run: ${{ inputs.dry-run }}
