name: npm pack

on:
    workflow_call:
        inputs:
            node-version:
                required: true
                type: string

            package-name:
                required: true
                type: string

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 1

            -   name: Use Node.js ${{ inputs.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ inputs.node-version }}

            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: node_modules
                    key: ${{ runner.os }}-node_modules

            -   name: npm install
                run: npm install --ignore-scripts

            -   name: Run build
                run: npm pack

            -   name: Upload artifact
                uses: actions/upload-artifact@v3
                with:
                    name: package
                    path: ${{ inputs.package-name }}-*.tgz
